=== stratosphr/workflowverification/src/main/resources/examples/Hadara/specification.dtd
<!ELEMENT specification (transition|conjunction|disjunction|negation)>
<!ATTLIST specification name CDATA #REQUIRED>
<!ATTLIST specification type (may|must) #REQUIRED>
<!ELEMENT transition EMPTY>
<!ATTLIST transition name CDATA #REQUIRED>
<!ELEMENT conjunction (transition|conjunction|disjunction|negation)+>
<!ELEMENT disjunction (transition|conjunction|disjunction|negation)+>
<!ELEMENT negation (transition|conjunction|disjunction|negation)>

=== stratosphr/workflowverification/src/main/resources/examples/mail/specifications/mail4.xml
<?xml version = "1.0" ?>
<!DOCTYPE specification SYSTEM "../../specification.dtd">

<specification name="specification4" type="may">
    <negation>
        <conjunction>
            <transition name="split"/>
            <transition name="pseudo"/>
            <transition name="mdp"/>
            <transition name="valider"/>
            <transition name="deconnecter"/>
        </conjunction>
    </negation>
</specification>

=== stratosphr/workflowverification/src/main/resources/mail/specifications/specification2.xml
<?xml version = "1.0" ?>
<!DOCTYPE specification SYSTEM "../../specification.dtd">

<!-- and[t1, not[or[t2, t3]], or[t2, t4, and[not[t4], t5]]] -->

<specification name="specification2" type="may">
    <conjunction>
        <transition name="split"/>
        <transition name="pseudo"/>
        <transition name="mdp"/>
        <transition name="valider"/>
        <transition name="consulter"/>
        <transition name="deconnecter"/>
    </conjunction>
</specification>

=== stratosphr/workflowverification/src/main/resources/examples/Old/coherent/specifications/specification1.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE specification SYSTEM "../../specification.dtd">

<specification type="may" name="specification1">
    <conjunction>
        <transition name="CRITSIT_navigateToSearch"/>
        <transition name="CRITSIT_backendSendTo"/>
        <transition name="CRITSIT_backendValidDispatch"/>
        <transition name="CRITSIT_verifyBackEndControlsStatus"/>
        <transition name="T38"/>
        <transition name="SR_navigateToSRCreation"/>
        <transition name="SR_navigateToSearch"/>
        <transition name="SR_frontEndAnalyse"/>
        <transition name="T34"/>
        <transition name="SR_backEnd2Verify"/>
        <transition name="T39"/>
        <transition name="T36"/>
    </conjunction>
</specification>

=== stratosphr/workflowverification/src/main/resources/examples/Old/big_siphonMG/specifications/specification1.xml
<?xml version = "1.0" ?>
<!DOCTYPE specification SYSTEM "../../specification.dtd">
<specification name="specification1" type="may">
    <disjunction>
        <transition name="T0"/>
        <transition name="T1"/>
        <transition name="T2"/>
        <transition name="T3"/>
        <transition name="T4"/>
        <transition name="T5"/>
        <transition name="T6"/>
        <transition name="T7"/>
        <transition name="T8"/>
        <transition name="T9"/>
        <transition name="T10"/>
        <transition name="T11"/>
    </disjunction>
</specification>

=== stratosphr/workflowverification/src/main/resources/examples/mail/specifications/mail1.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE specification SYSTEM "../../specification.dtd">

<specification type="must" name="mail1">
    <conjunction>
        <transition name="split"/>
        <transition name="pseudo"/>
        <transition name="mdp"/>
        <transition name="valider"/>
        <negation>
            <transition name="consulter"/>
        </negation>
        <transition name="deconnecter"/>
    </conjunction>
</specification>

=== stratosphr/workflowverification/src/main/resources/examples/reflexive/specifications/specification1.xml
<?xml version = "1.0" ?>
<!DOCTYPE specification SYSTEM "../../specification.dtd">

<specification name="specification1" type="may">
    <conjunction>
        <transition name="T1"/>
        <transition name="T2"/>
        <transition name="T3"/>
        <transition name="T4"/>
        <transition name="T5"/>
        <transition name="T6"/>
        <transition name="T7"/>
        <transition name="T8"/>
        <transition name="T9"/>
        <transition name="T10"/>
        <transition name="T11"/>
        <transition name="T12"/>
        <transition name="T13"/>
        <transition name="T14"/>
    </conjunction>
</specification>

=== stratosphr/workflowverification/src/main/resources/examples/mail/specifications/mail2.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE specification SYSTEM "../../specification.dtd">

<specification type="may" name="mail2">
    <conjunction>
        <transition name="split"/>
        <transition name="pseudo"/>
        <transition name="mdp"/>
        <transition name="valider"/>
        <disjunction>
            <negation>
                <transition name="consulter"/>
            </negation>
            <transition name="consulter"/>
        </disjunction>
        <transition name="deconnecter"/>
    </conjunction>
</specification>

=== stratosphr/workflowverification/src/main/resources/mail/specifications/specification1.xml
<?xml version = "1.0" ?>
<!DOCTYPE specification SYSTEM "../../specification.dtd">

<!-- and[split, not[or[pseudo, mdp]], or[pseudo, valider, and[not[valider], consulter]]] -->

<specification name="specification1" type="must">
    <conjunction>
        <transition name="split"/>
        <negation>
            <disjunction>
                <transition name="pseudo"/>
                <transition name="mdp"/>
            </disjunction>
        </negation>
        <disjunction>
            <transition name="pseudo"/>
            <transition name="valider"/>
            <conjunction>
                <negation>
                    <transition name="valider"/>
                </negation>
                <transition name="consulter"/>
            </conjunction>
        </disjunction>
        <transition name="split"/>
        <negation>
            <disjunction>
                <transition name="pseudo"/>
                <transition name="mdp"/>
            </disjunction>
        </negation>
        <disjunction>
            <transition name="pseudo"/>
            <transition name="valider"/>
            <conjunction>
                <negation>
                    <transition name="valider"/>
                </negation>
                <transition name="consulter"/>
            </conjunction>
        </disjunction>
        <transition name="split"/>
        <negation>
            <disjunction>
                <transition name="pseudo"/>
                <transition name="mdp"/>
            </disjunction>
        </negation>
        <disjunction>
            <transition name="pseudo"/>
            <transition name="valider"/>
            <conjunction>
                <negation>
                    <transition name="valider"/>
                </negation>
                <transition name="consulter"/>
            </conjunction>
        </disjunction>
        <transition name="split"/>
        <negation>
            <disjunction>
                <transition name="pseudo"/>
                <transition name="mdp"/>
            </disjunction>
        </negation>
        <disjunction>
            <transition name="pseudo"/>
            <transition name="valider"/>
            <conjunction>
                <negation>
                    <transition name="valider"/>
                </negation>
                <transition name="consulter"/>
            </conjunction>
        </disjunction>
        <transition name="split"/>
        <negation>
            <disjunction>
                <transition name="pseudo"/>
                <transition name="mdp"/>
            </disjunction>
        </negation>
        <disjunction>
            <transition name="pseudo"/>
            <transition name="valider"/>
            <conjunction>
                <negation>
                    <transition name="valider"/>
                </negation>
                <transition name="consulter"/>
            </conjunction>
        </disjunction>
        <transition name="split"/>
        <negation>
            <disjunction>
                <transition name="pseudo"/>
                <transition name="mdp"/>
            </disjunction>
        </negation>
        <disjunction>
            <transition name="pseudo"/>
            <transition name="valider"/>
            <conjunction>
                <negation>
                    <transition name="valider"/>
                </negation>
                <transition name="consulter"/>
            </conjunction>
        </disjunction>
    </conjunction>
</specification>
